extern int adc();
extern int ingreso();
extern int choice();
extern int internal(int c);
extern int external();
extern int fantastic();
extern int carrera();
extern int apilada();
extern int choque();
extern int kbhit();
extern int sec1();
extern int sec2();
extern int yuta();
extern int competencia();
extern int intensidad();
extern int contador();
