extern int adc();
extern int ingreso();
extern int choice();
extern void internal(int c);
extern int external();
extern void fantastic(int c);
extern void carrera(int c);
extern void apilada(int c);
extern void choque(int c);
extern int kbhit();
extern void sec1();
extern void sec2();
extern void yuta(int c);
extern void competencia(int c);
extern void intensidad(int c);
extern void contador(int c);
